[Interface]
PrivateKey = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
Address = 2602:f83b:886:4ea5:f738:e21c:930d:bc34/128
DNS = 2001:4860:4860::8888, 2001:4860:4860::8844

[Peer]
PublicKey = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
AllowedIPs = ::/1, 8000::/1
Endpoint = example.invalid:38047
PersistentKeepalive = 25
